name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - gemfile: rails-7.1.Gemfile
            rails_version: 7.1
            ruby_version: 3.1
          - gemfile: rails-7.2.Gemfile
            rails_version: 7.2
            ruby_version: 3.2
          - gemfile: rails-8.0.Gemfile
            rails_version: 8.0
            ruby_version: 3.3
    env:
      BUNDLE_GEMFILE: gemfiles/${{matrix.gemfile}}
      RAILS_VERSION: ${{ matrix.rails_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
          cache-version: 1
      - name: Run tests
        run: bundle exec rake test
