name: Test
on: [
  push,
  pull_request
]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - gemfile: rails-6.0.Gemfile
            rails_version: 6.0
          - gemfile: rails-6.1.Gemfile
            rails_version: 6.1
          - gemfile: rails-7.0.Gemfile
            rails_version: 7.0
          - gemfile: rails-7.1.Gemfile
            rails_version: 7.1
    env:
      BUNDLE_GEMFILE: gemfiles/${{matrix.gemfile}}
      RAILS_VERSION: ${{ matrix.rails_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          cache-version: 1
      - name: Run tests
        run: bundle exec rake test
